Use typed assignment instead of declaring floating variables
red-hat-storage/managed-fusion-agent pull request #22
Opened 2023-03-20 15:25 UTC by bindrad

2023-03-20 21:30 UTC, nb-ohad requested changes

2023-03-20 21:30 UTC, nb-ohad commented on controllers/managedfusionoffering_controller.go
>  	valid := true
Lets change that to `isValid`

2023-03-20 21:30 UTC, nb-ohad commented on controllers/managedfusionoffering_controller.go
>  	var err error
Reverse the order.
```suggestion
	var err error
	var usableCapacityInTiB int
```

2023-03-21 05:50 UTC, leelavg approved these changes

2023-03-21 10:12 UTC, ezio-auditore approved these changes

2023-03-21 18:24 UTC, nb-ohad approved these changes

2023-03-21 18:25 UTC, merged