Exit when CRDs are found for the first time to register with watches
red-hat-storage/managed-fusion-agent pull request #29
Opened 2023-03-24 16:25 UTC by bindrad

To build the cache CRDs for the offering should exist in the cluster but Agent installs the offering and then CRDs are created into the cluster. Because of this, the manager was not able to start.

So as a quick fix, we can run the controller initially to just install the offering(without watching offering resources) and then kill the container and re-run it with the offering watches.

2023-03-25 10:15 UTC, nb-ohad commented
Please add to the description a link to the github issue capturing the problem

2023-03-25 10:29 UTC, nb-ohad requested changes

2023-03-25 10:29 UTC, nb-ohad commented on controllers/managedfusionoffering_controller.go
> +	}
We have an established way to check for CRD existence. It was added with the SDN/OVN contribution a couple of months back on the original deployer repo. Please use this

https://github.com/red-hat-storage/ocs-osd-deployer/blob/main/controllers/managedocs_controller.go#L323-L328


Also, why is this implemented at the offering reconciler level where it is a fix for df add watches? This should go into dfSetupWatches. This all hack should be internal to the DF offering.

2023-03-25 10:29 UTC, nb-ohad commented on controllers/managedfusionoffering_controller.go
> +}
As of the last comment
```suggestion
```

2023-03-25 10:29 UTC, nb-ohad commented on controllers/managedfusionoffering_controller.go
> +	return ctrl.Result{}, nil
All of this code is very specific for DF, even if it does not say DF in the variable names, we should not do that. For this workaround, only the actual offering should know if it needs a restart or not and that code should go into the dfReconcile code at the start. But the reconciler should implement an `r.Exist()` function to allow the offering to exit without using a hack.  
```suggestion
	if result, err := pluginReconcile(r, r.managedFusionOffering); err != nil {
		return ctrl.Result{}, fmt.Errorf("An error was encountered during reconcile: %v", err)
	} else {
		return result, nil
	}
```

2023-03-28 16:54 UTC, nb-ohad commented on controllers/managedfusionoffering_controller.go
> +	DoesCRDExistsAtStart  bool
@leelavg You cannot wait in an init container for something that the same entity needs to initiate the installation for

2023-04-19 12:26 UTC, bindrad commented
https://github.com/red-hat-storage/managed-fusion-agent/pull/35 implements the workaround so closing this PR

2023-05-08 05:18 UTC, leelavg commented
should be closed in favour of #54?

2023-05-09 07:33 UTC, bindrad commented
closed in favour of https://github.com/red-hat-storage/managed-fusion-agent/pull/54

2023-05-09 07:33 UTC, closed without merging